"""empty message

Revision ID: 116be73789e6
Revises: 43c1f8bdd503
Create Date: 2017-12-15 23:37:00.587000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116be73789e6'
down_revision = '43c1f8bdd503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'articles', 'categories', ['second_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    # ### end Alembic commands ###
