"""empty message

Revision ID: 33dbed2961c4
Revises: a4e340e06208
Create Date: 2017-12-15 17:26:49.322000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33dbed2961c4'
down_revision = 'a4e340e06208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('articles', sa.Column('keys', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'keys')
    op.drop_column('articles', 'description')
    # ### end Alembic commands ###
