"""empty message

Revision ID: 35fe99086224
Revises: af20c0981bee
Create Date: 2017-12-15 23:26:16.747000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35fe99086224'
down_revision = 'af20c0981bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('first_category_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('second_category_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'articles_ibfk_1', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'categories', ['first_category_id'], ['id'])
    op.drop_column('articles', 'category_id')
    op.drop_column('articles', 'father_category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('father_category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key(u'articles_ibfk_1', 'articles', 'categories', ['category_id'], ['id'])
    op.drop_column('articles', 'second_category_id')
    op.drop_column('articles', 'first_category_id')
    # ### end Alembic commands ###
