"""empty message

Revision ID: 43c1f8bdd503
Revises: 35fe99086224
Create Date: 2017-12-15 23:28:09.767000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43c1f8bdd503'
down_revision = '35fe99086224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'body_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('body_html', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
