"""empty message

Revision ID: a4e340e06208
Revises: 48950aa0b307
Create Date: 2017-12-15 16:19:21.107000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e340e06208'
down_revision = '48950aa0b307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('body_html', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'body_html')
    # ### end Alembic commands ###
