"""empty message

Revision ID: af20c0981bee
Revises: 33dbed2961c4
Create Date: 2017-12-15 23:20:19.683000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af20c0981bee'
down_revision = '33dbed2961c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('father_category_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'father_category_id')
    # ### end Alembic commands ###
